### ISSUE TITLE
[NEW VERSION] EDC v0.1.2 / v0.2.0

### ISSUE THREAD

**Issue by fhennig** [stackabletech/edc-operator#22]
**Which new version of EDC should we support?**

The EDC is now released as non-alpha versions.

A new `jar` should be built and published here: https://github.com/stackabletech/product-config

IONOS did updates to 0.1.2, so we can use that: https://github.com/Digital-Ecosystems/edc-ionos-s3/commit/be2f6d9fc3dfc1fa20b677418c30a31843d6f5d7

Status:
- changes have been copied to our repo and gradle builds fine
- docker image built
- demo containers start up
- demo file transfer working
- which version should this be published under? Keep the image in sandbox or not?

To test:
- kind load images etc. (having built docker image with python -m image_tools.bake --product edc --image 0.0.0-dev)
- create buckets etc.
- change image name in demo.yaml
- make start-dev (starts provider/consumer and operator)
- make file-exchange
- start logging stack and check that opensearch contains output

**Comment by lfrancke** [comment]
This is in Done but not Closed. Can it be closed?

**Comment by fhennig** [comment]
Yes, sorry!
